
trigger:
  branches:
    include:
      - main   # or your main branch name

pool:
  vmImage: 'Default'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK'

- script: dotnet restore backend/YourBackendProject.csproj
  displayName: 'Restore dependencies'

- script: dotnet build backend/YourBackendProject.csproj --configuration Release --no-restore
  displayName: 'Build project'


